services:
  app:
    image: edefrutos/node-base-template:latest
    ports:
      - "${HOST_PORT:-5080}:${PORT:-3000}"
    environment:
      NODE_ENV: production
      PORT: ${PORT:-3000}
    restart: unless-stopped